const data = {
	ALLEY: ["ALLEY", "ALLEE", "ALY"],
	ANEX: ["ANEX", "ANNEX", "ANNX", "ANX"],
	ARCADE: ["ARCADE", "ARC"],
	AVENUE: ["AVENUE", "AV", "AVE", "AVEN", "AVENU", "AVENUE", "AVN", "AVNUE"],
	BAYOU: ["BAYOU", "BAYOO", "BYU"],
	BEACH: ["BEACH", "BCH"],
	BEND: ["BEND", "BEND", "BND"],
	BLUFF: ["BLUFF", "BLF", "BLUF", "BLUFF", "BLUFFS", "BLUFFS", "BLFS"],
	BOTTOM: ["BOTTOM", "BOT", "BTM", "BOTTM", "BOTTOM"],
	BOULEVARD: ["BOULEVARD", "BLVD", "BOUL", "BOULEVARD", "BOULV"],
	BRANCH: ["BRANCH", "BR", "BRNCH", "BRANCH"],
	BRIDGE: ["BRIDGE", "BRDGE", "BRG", "BRG", "BRIDGE"],
	BROOK: ["BROOK", "BRK", "BRK", "BROOK", "BROOKS", "BROOKS", "BRKS"],
	BURG: ["BURG", "BURG", "BG", "BURGS", "BURGS", "BGS"],
	BYPASS: ["BYPASS", "BYP", "BYP", "BYPA", "BYPAS", "BYPASS", "BYPS"],
	CAMP: ["CAMP", "CP", "CMP"],
	CANYON: ["CANYON", "CANYN", "CYN", "CNYN"],
	CAPE: ["CAPE", "CPE"],
	CAUSEWAY: ["CAUSEWAY", "CAUSWA", "CSWY"],
	CENTER: ["CENTER", "CEN", "CTR", "CENT", "CENTR", "CENTRE", "CNTER", "CNTR", "CENTERS", "CTRS"],
	CIRCLE: ["CIRCLE", "CIR", "CIRC", "CIRCL", "CIRCLE", "CRCL", "CRCLE", "CIRCLES", "CIRS"],
	CLIFF: ["CLIFF", "CLF", "CLF", "CLIFF", "CLIFFS", "CLFS", "CLFS", "CLIFFS"],
	CLUB: ["CLUB", "CLB", "CLB"],
};

const stTypeAbbr2Full = {
	ALLEY: "ALLEY",
	ALLEE: "ALLEY",
	ALY: "ALLEY",
	ANEX: "ANEX",
	ANNEX: "ANEX",
	ANNX: "ANEX",
	ANX: "ANEX",
	ARCADE: "ARCADE",
	ARC: "ARCADE",
	AVENUE: "AVENUE",
	AV: "AVENUE",
	AVE: "AVENUE",
	AVEN: "AVENUE",
	AVENU: "AVENUE",
	AVN: "AVENUE",
	AVNUE: "AVENUE",
	BAYOU: "BAYOU",
	BAYOO: "BAYOU",
	BYU: "BAYOU",
	BEACH: "BEACH",
	BCH: "BEACH",
	BEND: "BEND",
	BND: "BEND",
	BLUFF: "BLUFF",
	BLF: "BLUFF",
	BLUF: "BLUFF",
	BLUFFS: "BLUFFS",
	BOT: "BOTTOM",
	BTM: "BOTTOM",
	BOTTM: "BOTTOM",
	BOULEVARD: "BOULEVARD",
	BLVD: "BOULEVARD",
	BR: "BRANCH",
	BRDGE: "BRIDGE",
	BRK: "BROOK",
	BROOKS: "BROOKS",
	BURG: "BURG",
	BURGS: "BURGS",
	BYP: "BYPASS",
	BYPA: "BYPASS",
	BYPAS: "BYPASS",
	BYPASS: "BYPASS",
	BYPS: "BYPASS",
	CAMP: "CAMP",
	CP: "CAMP",
	CMP: "CAMP",
	CANYN: "CANYON",
	CANYON: "CANYON",
	CNYN: "CANYON",
	CAPE: "CAPE",
	CPE: "CAPE",
	CAUSEWAY: "CAUSEWAY",
	CAUSWA: "CAUSEWAY",
	CSWY: "CAUSEWAY",
	CEN: "CENTER",
	CENT: "CENTER",
	CENTER: "CENTER",
	CENTR: "CENTER",
	CENTRE: "CENTER",
	CNTER: "CENTER",
	CNTR: "CENTER",
	CTR: "CENTER",
	CENTERS: "CENTERS",
	CIR: "CIRCLE",
	CIRC: "CIRCLE",
	CIRCL: "CIRCLE",
	CIRCLE: "CIRCLE",
	CRCL: "CIRCLE",
	CRCLE: "CIRCLE",
	CIRCLES: "CIRCLES",
	CLF: "CLIFF",
	CLIFF: "CLIFF",
	CLFS: "CLIFFS",
	CLIFFS: "CLIFFS",
	CLUB: "CLB",
	COMMON: "COMMON",
	COMMONS: "COMMONS",
	CORNER: "COR",
	CORNERS: "CORNERS",
	COURSE: "COURSE",
	COURT: "COURT",
	COURTS: "COURTS",
	COVE: "COVE",
	COVES: "COVES",
	CREEK: "CREEK",
	CRESCENT: "CRESCENT",
	CREST: "CREST",
	CROSSING: "CROSSING",
	CROSSROAD: "CROSSROAD",
	CROSSROADS: "CROSSROADS",
	CURVE: "CURVE",
	DALE: "DALE",
	DAM: "DAM",
	DIVIDE: "DIVIDE",
	DRIVE: "DRIVE",
	DRIVES: "DRIVES",
	ESTATE: "ESTATE",
	ESTATES: "ESTATES",
	EXPRESSWAY: "EXPRESSWAY",
	EXTENSION: "EXTENSION",
	EXTENSIONS: "EXTENSIONS",
	FALL: "FALL",
	FALLS: "FALLS",
	FERRY: "FERRY",
	FIELD: "FIELD",
	FIELDS: "FIELDS",
	FLAT: "FLAT",
	FLATS: "FLATS",
	FORD: "FORD",
	FORDS: "FORDS",
	FOREST: "FOREST",
	FORGE: "FORGE",
	FORGES: "FORGES",
	FORK: "FORK",
	FORKS: "FORKS",
	FORT: "FORT",
	FREEWAY: "FREEWAY",
	GARDEN: "GARDEN",
	GARDENS: "GARDENS",
	GATEWAY: "GATEWAY",
	GLEN: "GLEN",
	GLENS: "GLENS",
	GREEN: "GREEN",
	GREENS: "GREENS",
	GROVE: "GROVE",
	GROVES: "GROVES",
	HARBOR: "HARBOR",
	HARBORS: "HARBORS",
	HAVEN: "HAVEN",
	HEIGHTS: "HEIGHTS",
	HIGHWAY: "HIGHWAY",
	HILL: "HILL",
	HILLS: "HILLS",
	HOLLOW: "HOLLOW",
	INLET: "INLET",
	ISLAND: "ISLAND",
	ISLANDS: "ISLANDS",
	ISLE: "ISLE",
	JUNCTION: "JUNCTION",
	JUNCTIONS: "JUNCTIONS",
	KEY: "KEY",
	KEYS: "KEYS",
	KNOLL: "KNOLL",
	KNOLLS: "KNOLLS",
	LAKE: "LAKE",
	LAKES: "LAKES",
	LAND: "LAND",
	LANDING: "LANDING",
	LANE: "LANE",
	LIGHT: "LIGHT",
	LIGHTS: "LIGHTS",
	LOAF: "LOAF",
	LOCK: "LOCK",
	LOCKS: "LOCKS",
	LODGE: "LODGE",
	LOOP: "LOOP",
	MALL: "MALL",
	MANOR: "MANOR",
	MANORS: "MANORS",
	MEADOW: "MEADOW",
	MEADOWS: "MEADOWS",
	MEDOWS: "MEADOWS",
	MEWS: "MEWS",
	MILL: "MILL",
	MILLS: "MILLS",
	MISSION: "MISSION",
	MISSN: "MISSION",
	MSSN: "MISSION",
	MOUNTAIN: "MOUNTAIN",
	MOUNT: "MOUNTAIN",
	MNTAIN: "MOUNTAIN",
	MNTN: "MOUNTAIN",
	MOUNTAIN: "MOUNTAIN",
	MOUNTIN: "MOUNTAIN",
	MT: "MOUNTAIN",
	MTIN: "MOUNTAIN",
	MNTNS: "MOUNTAINS",
	MOUNTAINS: "MOUNTAINS",
	NCK: "NECK",
	NCK: "NECK",
	ORCH: "ORCHARD",
	OVAL: "OVAL",
	OVERPASS: "OVERPASS",
	PARK: "PARK",
	PRK: "PARK",
	PARKS: "PARKS",
	PARKWAY: "PARKWAY",
	PARKWY: "PARKWAY",
	PKWAY: "PARKWAY",
	PKWY: "PARKWAY",
	PKY: "PARKWAY",
	PARKWAYS: "PARKWAYS",
	PKWYS: "PARKWAYS",
	PASS: "PASS",
	PASSAGE: "PASSAGE",
	PATH: "PATH",
	PATHS: "PATH",
	PIKE: "PIKE",
	PIKES: "PIKE",
	PINE: "PINE",
	PINES: "PINES",
	PNES: "PINES",
	PL: "PLACE",
	PLAIN: "PLAIN",
	PLN: "PLAIN",
	PLAINS: "PLAINS",
	PLNS: "PLAINS",
	PLAZA: "PLAZA",
	PLZ: "PLAZA",
	PLZA: "PLAZA",
	POINT: "POINT",
	PT: "POINT",
	POINTS: "POINTS",
	PTS: "POINTS",
	PORT: "PORT",
	PRT: "PORT",
	PORTS: "PORTS",
	PRTS: "PORTS",
	PR: "PRAIRIE",
	PRAIRIE: "PRAIRIE",
	PRR: "PRAIRIE",
	RAD: "RADIAL",
	RADIAL: "RADIAL",
	RADIEL: "RADIAL",
	RADL: "RADIAL",
	RAMP: "RAMP",
	RANCH: "RANCH",
	RANCHES: "RANCH",
	RNCH: "RANCH",
	RNCHS: "RANCH",
	RAPID: "RAPID",
	RPD: "RAPID",
	RAPIDS: "RAPIDS",
	RPDS: "RAPIDS",
	REST: "REST",
	RST: "REST",
	RDG: "RIDGE",
	RDGE: "RIDGE",
	RIDGE: "RIDGE",
	RDGS: "RIDGES",
	RIDGES: "RIDGES",
	RIV: "RIVER",
	RIVER: "RIVER",
	RVR: "RIVER",
	RIVR: "RIVER",
	RD: "ROAD",
	ROAD: "ROAD",
	ROADS: "ROADS",
	RDS: "ROADS",
	ROUTE: "ROUTE",
	ROW: "ROW",
	RUE: "RUE",
	RUN: "RUN",
	SHL: "SHOAL",
	SHOAR: "SHORE",
	SHOARS: "SHORES",
	SKYWAY: "SKYWAY",
	SPG: "SPRING",
	SPNG: "SPRING",
	SPRNG: "SPRING",
	SPGS: "SPRINGS",
	SPNGS: "SPRINGS",
	SPUR: "SPUR",
	SPURS: "SPURS",
	SQ: "SQUARE",
	SQR: "SQUARE",
	SQRE: "SQUARE",
	SQU: "SQUARE",
	SQRS: "SQUARES",
	STA: "STATION",
	STATION: "STATION",
	STATN: "STATION",
	STN: "STATION",
	STRA: "STRAVENUE",
	STRAV: "STRAVENUE",
	STRAVEN: "STRAVENUE",
	STRAVENUE: "STRAVENUE",
	STRAVN: "STRAVENUE",
	STRVN: "STRAVENUE",
	STRVNUE: "STRAVENUE",
	STREAM: "STREAM",
	STREME: "STREAM",
	STRM: "STREAM",
	STREET: "STREET",
	STRT: "STREET",
	ST: "STREET",
	STR: "STREET",
	STREETS: "STREETS",
	SMT: "SUMMIT",
	SUMIT: "SUMMIT",
	SUMITT: "SUMMIT",
	SUMMIT: "SUMMIT",
	TER: "TERRACE",
	TERR: "TERRACE",
	TERRACE: "TERRACE",
	THROUGHWAY: "THROUGHWAY",
	TRACE: "TRACE",
	TRACES: "TRACE",
	TRCE: "TRACE",
	TRACK: "TRACK",
	TRACKS: "TRACK",
	TRAK: "TRACK",
	TRK: "TRACK",
	TRKS: "TRACK",
	TRAFFICWAY: "TRAFFICWAY",
	TRAIL: "TRAIL",
	TRAILS: "TRAIL",
	TRL: "TRAIL",
	TRLS: "TRAIL",
	TRAILER: "TRAILER",
	TRAILERS: "TRAILER",
	TRLR: "TRAILER",
	TRLRS: "TRAILER",
	TUNEL: "TUNNEL",
	TRNPK: "TURNPIKE",
	UNDERPASS: "UNDERPASS",
	UN: "UNION",
	UNIONS: "UNIONS",
	VALLEY: "VALLEY",
	VALLY: "VALLEY",
	VLLY: "VALLEY",
	VLY: "VALLEY",
	VALLEYS: "VALLEYS",
	VLYS: "VALLEYS",
	VDCT: "VIADUCT",
	VIA: "VIADUCT",
	VIADCT: "VIADUCT",
	VIADUCT: "VIADUCT",
	VIEW: "VIEW",
	VW: "VIEW",
	VIEWS: "VIEWS",
	VWS: "VIEWS",
	VILL: "VILLAGE",
	VILLAG: "VILLAGE",
	VILLAGE: "VILLAGE",
	VILLG: "VILLAGE",
	VILLIAGE: "VILLAGE",
	VLG: "VILLAGE",
	VILLAGES: "VILLAGES",
	VLGS: "VILLAGES",
	VILLE: "VILLE",
	VL: "VILLE",
	VIS: "VISTA",
	VIST: "VISTA",
	VISTA: "VISTA",
	VST: "VISTA",
	VSTA: "VISTA",
	WALK: "WALK",
	WALKS: "WALKS",
	WALL: "WALL",
	WY: "WAY",
	WAY: "WAY",
	WAYS: "WAYS",
	WELL: "WELL",
	WELLS: "WELLS",
	WLS: "WELLS",
};

const stTypeFull2PostalAbbr = {
	ALLEY: "ALY",
	ANEX: "ANX",
	ARCADE: "ARC",
	AVENUE: "AVE",
	BAYOU: "BYU",
	BEACH: "BCH",
	BEND: "BND",
	BLUFF: "BLF",
	BLUFFS: "BLFS",
	BOTTOM: "BTM",
	BOULEVARD: "BLVD",
	BRANCH: "BR",
	BRIDGE: "BRG",
	BROOK: "BRK",
	BROOKS: "BRKS",
	BURG: "BG",
	BURGS: "BGS",
	BYPASS: "BYP",
	CAMP: "CP",
	CANYON: "CYN",
	CAPE: "CPE",
	CAUSEWAY: "CSWY",
	CENTER: "CTR",
	CENTERS: "CTRS",
	CIRCLE: "CIR",
	CIRCLES: "CIRS",
	CLIFF: "CLF",
	CLIFFS: "CLFS",
	CLUB: "CLB",
	COMMON: "CMN",
	COMMONS: "CMNS",
	CORNER: "COR",
	CORNERS: "CORS",
	COURSE: "CRSE",
	COURT: "CT",
	COURTS: "CTS",
	COVE: "CV",
	COVES: "CVS",
	CREEK: "CRK",
	CRESCENT: "CRES",
	CREST: "CRST",
	CROSSING: "XING",
	CROSSROAD: "XRD",
	CROSSROADS: "XRDS",
	CURVE: "CURV",
	DALE: "DL",
	DAM: "DM",
	DIVIDE: "DV",
	DRIVE: "DR",
	DRIVES: "DRS",
	ESTATE: "EST",
	ESTATES: "ESTS",
	EXPRESSWAY: "EXPY",
	EXTENSION: "EXT",
	EXTENSIONS: "EXTS",
	FALL: "FALL",
	FALLS: "FLS",
	FERRY: "FRY",
	FIELD: "FLD",
	FIELDS: "FLDS",
	FLAT: "FLT",
	FLATS: "FLTS",
	FORD: "FRD",
	FORDS: "FRDS",
	FOREST: "FRST",
	FORGE: "FRG",
	FORGES: "FRGS",
	FORK: "FRK",
	FORKS: "FRKS",
	FORT: "FT",
	FREEWAY: "FWY",
	GARDEN: "GDN",
	GARDENS: "GDNS",
	GATEWAY: "GTWY",
	GLEN: "GLN",
	GLENS: "GLNS",
	GREEN: "GRN",
	GREENS: "GRNS",
	GROVE: "GRV",
	GROVES: "GRVS",
	HARBOR: "HBR",
	HARBORS: "HBRS",
	HAVEN: "HVN",
	HEIGHTS: "HTS",
	HIGHWAY: "HWY",
	HILL: "HL",
	HILLS: "HLS",
	HOLLOW: "HOLW",
	INLET: "INLT",
	ISLAND: "IS",
	ISLANDS: "ISS",
	ISLE: "ISLE",
	JUNCTION: "JCT",
	JUNCTIONS: "JCTS",
	KEY: "KY",
	KEYS: "KYS",
	KNOLL: "KNL",
	KNOLLS: "KNLS",
	LAKE: "LK",
	LAKES: "LKS",
	LAND: "LAND",
	LANDING: "LNDG",
	LANE: "LN",
	LIGHT: "LGT",
	LIGHTS: "LGTS",
	LOAF: "LF",
	LOCK: "LCK",
	LOCKS: "LCKS",
	LODGE: "LDG",
	LOOP: "LOOP",
	MALL: "MALL",
	MANOR: "MNR",
	MANORS: "MNRS",
	MEADOW: "MDW",
	MEADOWS: "MDWS",
	MEWS: "MEWS",
	MILL: "ML",
	MILLS: "MLS",
	MISSION: "MSN",
	MOTORWAY: "MTWY",
	MOUNT: "MT",
	MOUNTAIN: "MTN",
	MOUNTAINS: "MTNS",
	NECK: "NCK",
	ORCHARD: "ORCH",
	OVAL: "OVAL",
	OVERPASS: "OPAS",
	PARK: "PARK",
	PARKS: "PARK",
	PARKWAY: "PKWY",
	PARKWAYS: "PKWY",
	PASS: "PASS",
	PASSAGE: "PSGE",
	PATH: "PATH",
	PIKE: "PIKE",
	PINE: "PNE",
	PINES: "PNES",
	PLACE: "PL",
	PLAIN: "PLN",
	PLAINS: "PLNS",
	PLAZA: "PLZ",
	POINT: "PT",
	POINTS: "PTS",
	PORT: "PRT",
	PORTS: "PRTS",
	PRAIRIE: "PR",
	RADIAL: "RADL",
	RAMP: "RAMP",
	RANCH: "RNCH",
	RAPID: "RPD",
	RAPIDS: "RPDS",
	REST: "RST",
	RIDGE: "RDG",
	RIDGES: "RDGS",
	RIVER: "RIV",
	ROAD: "RD",
	ROADS: "RDS",
	ROUTE: "RTE",
	ROW: "ROW",
	RUE: "RUE",
	RUN: "RUN",
	SHOAL: "SHL",
	SHOALS: "SHLS",
	SHORE: "SHR",
	SHORES: "SHRS",
	SKYWAY: "SKWY",
	SPRING: "SPG",
	SPRINGS: "SPGS",
	SPUR: "SPUR",
	SPURS: "SPUR",
	SQUARE: "SQ",
	SQUARES: "SQS",
	STATION: "STA",
	STRAVENUE: "STRA",
	STREAM: "STRM",
	STREET: "ST",
	STREETS: "STS",
	SUMMIT: "SMT",
	TERRACE: "TER",
	THROUGHWAY: "TRWY",
	TRACE: "TRCE",
	TRACK: "TRAK",
	TRAFFICWAY: "TRFY",
	TRAIL: "TRL",
	TRAILER: "TRLR",
	TUNNEL: "TUNL",
	TURNPIKE: "TPKE",
	UNDERPASS: "UPAS",
	UNION: "UN",
	UNIONS: "UNS",
	VALLEY: "VLY",
	VALLEYS: "VLYS",
	VIADUCT: "VIA",
	VIEW: "VW",
	VIEWS: "VWS",
	VILLAGE: "VLG",
	VILLAGES: "VLGS",
	VILLE: "VL",
	VISTA: "VIS",
	WALK: "WALK",
	WALKS: "WALK",
	WALL: "WALL",
	WAY: "WAY",
	WAYS: "WAYS",
	WELL: "WL",
	WELLS: "WLS",
};

// function condenseObject(obj) {
// 	const condensedObj = {};
// 	for (const key in obj) {
// 		if (obj.hasOwnProperty(key)) {
// 			const value = obj[key];
// 			if (!condensedObj[value]) {
// 				condensedObj[value] = [key];
// 			} else {
// 				condensedObj[value].push(key);
// 			}
// 		}
// 	}
// 	return condensedObj;
// }

// const condensedArray = condenseObject(stTypeAbbr2Full);
// console.log(condensedArray);

const condensedArray = {
	ALLEY: ["ALLEY", "ALLEE", "ALY"],
	ANEX: ["ANEX", "ANNEX", "ANNX", "ANX"],
	ARCADE: ["ARCADE", "ARC"],
	AVENUE: ["AVENUE", "AV", "AVE", "AVEN", "AVENU", "AVN", "AVNUE"],
	BAYOU: ["BAYOU", "BAYOO", "BYU"],
	BEACH: ["BEACH", "BCH"],
	BEND: ["BEND", "BND"],
	BLUFF: ["BLUFF", "BLF", "BLUF"],
	BLUFFS: ["BLUFFS"],
	BOTTOM: ["BOT", "BTM", "BOTTM"],
	BOULEVARD: ["BOULEVARD", "BLVD"],
	BRANCH: ["BR"],
	BRIDGE: ["BRDGE"],
	BROOK: ["BRK"],
	BROOKS: ["BROOKS"],
	BURG: ["BURG"],
	BURGS: ["BURGS"],
	BYPASS: ["BYP", "BYPA", "BYPAS", "BYPASS", "BYPS"],
	CAMP: ["CAMP", "CP", "CMP"],
	CANYON: ["CANYN", "CANYON", "CNYN"],
	CAPE: ["CAPE", "CPE"],
	CAUSEWAY: ["CAUSEWAY", "CAUSWA", "CSWY"],
	CENTER: ["CEN", "CENT", "CENTER", "CENTR", "CENTRE", "CNTER", "CNTR", "CTR"],
	CENTERS: ["CENTERS"],
	CIRCLE: ["CIR", "CIRC", "CIRCL", "CIRCLE", "CRCL", "CRCLE"],
	CIRCLES: ["CIRCLES"],
	CLUB: ["CLB"],
	CLIFF: ["CLF", "CLIFF"],
	CLIFFS: ["CLFS", "CLIFFS"],
	COMMON: ["COMMON", "CMN"],
	COMMONS: ["COMMONS", "CMNS"],
	CORNER: ["COR", "CORNER"],
	CORNERS: ["CORS", "CORNERS"],
	COURSE: ["COURSE"],
	COURT: ["COURT", "CT"],
	COURTS: ["COURTS", "CTS"],
	COVE: ["COVE", "CV"],
	COVES: ["COVES", "CVS"],
	CREEK: ["CREEK", "CRK"],
	CRESCENT: ["CRESCENT"],
	CREST: ["CREST", "CRST"],
	CROSSING: ["CROSSING"],
	CROSSROAD: ["CROSSROAD"],
	CROSSROADS: ["CROSSROADS"],
	CURVE: ["CURVE"],
	DALE: ["DALE"],
	DAM: ["DAM"],
	DIVIDE: ["DIVIDE"],
	DRIVE: ["DRIVE", "DR", "DRIV"],
	DRIVES: ["DRIVES", "DRS"],
	ESTATE: ["ESTATE", "EST", "ESTAT"],
	ESTATES: ["ESTATES", "ESTS"],
	EXPRESSWAY: ["EXPRESSWAY", "EXP", "EXPR", "EXPW", "EXPY"],
	EXTENSION: ["EXTENSION", "EXT", "EXTN", "EXTNSN"],
	EXTENSIONS: ["EXTENSIONS", "EXTS"],
	FALL: ["FALL"],
	FALLS: ["FALLS"],
	FERRY: ["FERRY"],
	FIELD: ["FIELD"],
	FIELDS: ["FIELDS"],
	FLAT: ["FLAT"],
	FLATS: ["FLATS"],
	FORD: ["FORD"],
	FORDS: ["FORDS"],
	FOREST: ["FOREST"],
	FORGE: ["FORGE"],
	FORGES: ["FORGES"],
	FORK: ["FORK"],
	FORKS: ["FORKS"],
	FORT: ["FORT"],
	FREEWAY: ["FREEWAY"],
	GARDEN: ["GARDEN"],
	GARDENS: ["GARDENS"],
	GATEWAY: ["GATEWAY"],
	GLEN: ["GLEN"],
	GLENS: ["GLENS"],
	GREEN: ["GREEN"],
	GREENS: ["GREENS"],
	GROVE: ["GROVE"],
	GROVES: ["GROVES"],
	HARBOR: ["HARBOR"],
	HARBORS: ["HARBORS"],
	HAVEN: ["HAVEN"],
	HEIGHTS: ["HEIGHTS"],
	HIGHWAY: ["HIGHWAY"],
	HILL: ["HILL"],
	HILLS: ["HILLS"],
	HOLLOW: ["HOLLOW"],
	INLET: ["INLET"],
	ISLAND: ["ISLAND"],
	ISLANDS: ["ISLANDS"],
	ISLE: ["ISLE"],
	JUNCTION: ["JUNCTION"],
	JUNCTIONS: ["JUNCTIONS"],
	KEY: ["KEY"],
	KEYS: ["KEYS"],
	KNOLL: ["KNOLL"],
	KNOLLS: ["KNOLLS"],
	LAKE: ["LAKE"],
	LAKES: ["LAKES"],
	LAND: ["LAND"],
	LANDING: ["LANDING"],
	LANE: ["LANE"],
	LIGHT: ["LIGHT"],
	LIGHTS: ["LIGHTS"],
	LOAF: ["LOAF"],
	LOCK: ["LOCK"],
	LOCKS: ["LOCKS"],
	LODGE: ["LODGE"],
	LOOP: ["LOOP"],
	MALL: ["MALL"],
	MANOR: ["MANOR"],
	MANORS: ["MANORS"],
	MEADOW: ["MEADOW"],
	MEADOWS: ["MEADOWS", "MEDOWS"],
	MEWS: ["MEWS"],
	MILL: ["MILL"],
	MILLS: ["MILLS"],
	MISSION: ["MISSION", "MISSN", "MSSN"],
	MOUNTAIN: ["MOUNTAIN", "MOUNT", "MNTAIN", "MNTN", "MOUNTIN", "MT", "MTIN"],
	MOUNTAINS: ["MNTNS", "MOUNTAINS"],
	NECK: ["NCK"],
	ORCHARD: ["ORCH"],
	OVAL: ["OVAL"],
	OVERPASS: ["OVERPASS"],
	PARK: ["PARK", "PRK"],
	PARKS: ["PARKS"],
	PARKWAY: ["PARKWAY", "PARKWY", "PKWAY", "PKWY", "PKY"],
	PARKWAYS: ["PARKWAYS", "PKWYS"],
	PASS: ["PASS"],
	PASSAGE: ["PASSAGE"],
	PATH: ["PATH", "PATHS"],
	PIKE: ["PIKE", "PIKES"],
	PINE: ["PINE"],
	PINES: ["PINES", "PNES"],
	PLACE: ["PL"],
	PLAIN: ["PLAIN", "PLN"],
	PLAINS: ["PLAINS", "PLNS"],
	PLAZA: ["PLAZA", "PLZ", "PLZA"],
	POINT: ["POINT", "PT"],
	POINTS: ["POINTS", "PTS"],
	PORT: ["PORT", "PRT"],
	PORTS: ["PORTS", "PRTS"],
	PRAIRIE: ["PR", "PRAIRIE", "PRR"],
	RADIAL: ["RAD", "RADIAL", "RADIEL", "RADL"],
	RAMP: ["RAMP"],
	RANCH: ["RANCH", "RANCHES", "RNCH", "RNCHS"],
	RAPID: ["RAPID", "RPD"],
	RAPIDS: ["RAPIDS", "RPDS"],
	REST: ["REST", "RST"],
	RIDGE: ["RDG", "RDGE", "RIDGE"],
	RIDGES: ["RDGS", "RIDGES"],
	RIVER: ["RIV", "RIVER", "RVR", "RIVR"],
	ROAD: ["RD", "ROAD"],
	ROADS: ["ROADS", "RDS"],
	ROUTE: ["ROUTE"],
	ROW: ["ROW"],
	RUE: ["RUE"],
	RUN: ["RUN"],
	SHOAL: ["SHL", "SHOAL", "SHOL"],
	SHOALS: ["SHOALS", "SHLS", "SHOLS"],
	SHORE: ["SHOAR", "SHORE", "SHR"],
	SHORES: ["SHOARS", "SHORES", "SHRS"],
	SKYWAY: ["SKYWAY", "SKYWY"],
	SPRING: ["SPG", "SPNG", "SPRNG", "SPRING"],
	SPRINGS: ["SPGS", "SPNGS", "SPRINGS"],
	SPUR: ["SPUR"],
	SPURS: ["SPURS"],
	SQUARE: ["SQ", "SQR", "SQRE", "SQU", "SQUARE"],
	SQUARES: ["SQRS", "SQUARES"],
	STATION: ["STA", "STATION", "STATN", "STN"],
	STRAVENUE: ["STRA", "STRAV", "STRAVEN", "STRAVENUE", "STRAVN", "STRVN", "STRVNUE"],
	STREAM: ["STREAM", "STREME", "STRM"],
	STREET: ["STREET", "STRT", "ST", "STR"],
	STREETS: ["STREETS", "STS"],
	SUMMIT: ["SMT", "SUMIT", "SUMITT", "SUMMIT"],
	TERRACE: ["TER", "TERR", "TERRACE"],
	THROUGHWAY: ["THROUGHWAY", "THRUWAY", "THWAY", "TRWY"],
	TRACE: ["TRACE", "TRACES", "TRCE"],
	TRACK: ["TRACK", "TRACKS", "TRAK", "TRK", "TRKS"],
	TRAFFICWAY: ["TRAFFICWAY"],
	TRAIL: ["TRAIL", "TRAILS", "TRL", "TRLS"],
	TRAILER: ["TRAILER", "TRAILERS", "TRLR", "TRLRS"],
	TUNNEL: ["TUNEL", "TUNL", "TUNLS", "TUNNEL", "TUNNELS", "TUNNL"],
	TURNPIKE: ["TRNPK", "TURNPIKE", "TURNPK"],
	UNDERPASS: ["UNDERPASS"],
	UNION: ["UN", "UNION", "UNIONS", "UNS"],
	UNIONS: ["UNIONS", "UNS"],
	VALLEY: ["VALLEY", "VALLY", "VLLY", "VLY"],
	VALLEYS: ["VALLEYS", "VLYS"],
	VIADUCT: ["VDCT", "VIA", "VIADCT", "VIADUCT"],
	VIEW: ["VIEW", "VW"],
	VIEWS: ["VIEWS", "VWS"],
	VILLAGE: ["VILL", "VILLAG", "VILLAGE", "VILLG", "VILLIAGE", "VLG"],
	VILLAGES: ["VILLAGES", "VLGS"],
	VILLE: ["VILLE", "VL"],
	VISTA: ["VIS", "VIST", "VISTA", "VST", "VSTA"],
	WALK: ["WALK"],
	WALKS: ["WALKS"],
	WALL: ["WALL"],
	WAY: ["WY", "WAY"],
	WAYS: ["WAYS"],
	WELL: ["WELL"],
	WELLS: ["WELLS", "WLS"],
};

const names = {
	plaza: {
		abbr: ["PLZ", "PLZA"],
		full: "PLAZA",
		postal: "PLZ",
	},
	well: {
		abbr: ["WL"],
		full: "WELL",
		postal: "WL",
	},
};

function transform(obj1) {
	const obj2 = {};
	for (const [key, value] of Object.entries(obj1)) {
		const full = value[0];
		const abbr = value.slice(1);
		obj2[key.toLowerCase()] = { full, abbr, postal: "" };
	}
	return obj2;
}

// console.log(transform(condensedArray));

const condensedArrayFull = {
	alley: { full: "ALLEY", abbr: ["ALLEE", "ALY", "ALLY"], postal: "ALY" },
	anex: { full: "ANEX", abbr: ["ANNEX", "ANNX", "ANX"], postal: "ANX" },
	arcade: { full: "ARCADE", abbr: ["ARC"], postal: "ARC" },
	avenue: { full: "AVENUE", abbr: ["AVE", "AV", "AVEN", "AVENU", "AVN", "AVNU"], postal: "AVE" },
	bayou: { full: "BAYOU", abbr: ["BAYOO", "BYU"], postal: "BYU" },
	beach: { full: "BEACH", abbr: ["BCH"], postal: "BCH" },
	bend: { full: "BEND", abbr: ["BND"], postal: "BND" },
	bluff: { full: "BLUFF", abbr: ["BLF", "BLUF"], postal: "BLF" },
	bluffs: { full: "BLUFFS", abbr: ["BLFS", "BLUFS"], postal: "BLFS" },
	bottom: { full: "BOTTOM", abbr: ["BTM", "BOTTM", "BOT"], postal: "BTM" },
	boulevard: { full: "BOULEVARD", abbr: ["BLVD", "BOUL", "BOULV"], postal: "BLVD" },
	branch: { full: "BRANCH", abbr: ["BR", "BRNCH"], postal: "BR" },
	bridge: { full: "BRDGE", abbr: ["BRG", "BRDGE", "BRDG"], postal: "BRG" },
	brook: { full: "BROOK", abbr: ["BRK"], postal: "BRK" },
	brooks: { full: "BROOKS", abbr: ["BRKS"], postal: "BRKS" },
	burg: { full: "BURG", abbr: ["BG"], postal: "BG" },
	burgs: { full: "BURGS", abbr: ["BGS"], postal: "BGS" },
	bypass: { full: "BYPASS", abbr: ["BYPA", "BYPAS", "BYP", "BYPS"], postal: "BYP" },
	camp: { full: "CAMP", abbr: ["CP", "CMP"], postal: "CP" },
	canyon: { full: "CANYON", abbr: ["CANYN", "CNYN"], postal: "CYN" },
	cape: { full: "CAPE", abbr: ["CPE"], postal: "CPE" },
	causeway: { full: "CAUSEWAY", abbr: ["CAUSWA", "CSWY"], postal: "CSWY" },
	center: { full: "CENTER", abbr: ["CEN", "CENT", "CENTR", "CENTRE", "CNTER", "CNTR", "CTR"], postal: "CTR" },
	centers: { full: "CENTERS", abbr: ["CENS", "CENTS", "CENTRS", "CENTRES", "CNTERS", "CNTRS", "CTRS"], postal: "CTRS" },
	circle: { full: "CIRCLE", abbr: ["CIR", "CIRC", "CIRCL", "CIRCLE", "CRCL", "CRCLE"], postal: "CIR" },
	circles: { full: "CIRCLES", abbr: ["CIRS", "CIRCS", "CIRCLS", "CRCLS", "CRCLES"], postal: "CIRS" },
	cliff: { full: "CLIFF", abbr: ["CLF", "CLFF"], postal: "CLF" },
	cliffs: { full: "CLIFFS", abbr: ["CLFS"], postal: "CLFS" },
	club: { full: "CLUB", abbr: ["CLB"], postal: "CLB" },
	common: { full: "COMMON", abbr: ["CMN", "CMMN"], postal: "CMN" },
	commons: { full: "COMMONS", abbr: ["CMNS", "CMMNS"], postal: "CMNS" },
	corner: { full: "CORNER", abbr: ["COR"], postal: "COR" },
	corners: { full: "CORNERS", abbr: ["CORS"], postal: "CORS" },
	course: { full: "COURSE", abbr: ["CRSE"], postal: "CRSE" },
	court: { full: "COURT", abbr: ["CT"], postal: "CT" },
	courts: { full: "COURTS", abbr: ["CTS"], postal: "CTS" },
	cove: { full: "COVE", abbr: ["CV"], postal: "CV" },
	coves: { full: "COVES", abbr: ["CVS"], postal: "CVS" },
	creek: { full: "CREEK", abbr: ["CRK"], postal: "CRK" },
	crescent: { full: "CRESCENT", abbr: ["CRES", "CRSENT", "CRSNT"], postal: "CRES" },
	crest: { full: "CREST", abbr: ["CRST"], postal: "CRST" },
	crossing: { full: "CROSSING", abbr: ["CRSSNG", "CRSNG", "XING"], postal: "XING" },
	crossroad: { full: "CROSSROAD", abbr: ["XRD", "CRSRD"], postal: "XRD" },
	crossroads: { full: "CROSSROADS", abbr: ["XRDS", "CRSRDS"], postal: "XRDS" },
	curve: { full: "CURVE", abbr: ["CURV"], postal: "CURV" },
	dale: { full: "DALE", abbr: ["DL"], postal: "DL" },
	dam: { full: "DAM", abbr: ["DM"], postal: "DM" },
	divide: { full: "DIVIDE", abbr: ["DIV", "DV", "DVD"], postal: "DV" },
	drive: { full: "DRIVE", abbr: ["DR", "DRIV", "DRV"], postal: "DR" },
	drives: { full: "DRIVES", abbr: ["DRS", "DRIVS", "DRVS"], postal: "DRS" },
	estate: { full: "ESTATE", abbr: ["EST", "ESTAT"], postal: "EST" },
	estates: { full: "ESTATES", abbr: ["ESTS", "ESTATS"], postal: "ESTS" },
	expressway: { full: "EXPRESSWAY", abbr: ["EXP", "EXPR", "EXPW", "EXPY", "EXPRESS"], postal: "EXPY" },
	extension: { full: "EXTENSION", abbr: ["EXT", "EXTN", "EXTNSN", "EXTSN"], postal: "EXT" },
	extensions: { full: "EXTENSIONS", abbr: ["EXTS", "EXTNS", "EXTNSNS", "EXTSNS"], postal: "EXTS" },
	fall: { full: "FALL", abbr: ["FALL"], postal: "FALL" },
	falls: { full: "FALLS", abbr: ["FALLS", "FLS"], postal: "FLS" },
	ferry: { full: "FERRY", abbr: ["FRY", "FRRY"], postal: "FRY" },
	field: { full: "FIELD", abbr: ["FLD"], postal: "FLD" },
	fields: { full: "FIELDS", abbr: ["FLDS"], postal: "FLDS" },
	flat: { full: "FLAT", abbr: ["FLT"], postal: "FLT" },
	flats: { full: "FLATS", abbr: ["FLTS"], postal: "FLTS" },
	ford: { full: "FORD", abbr: ["FRD"], postal: "FRD" },
	fords: { full: "FORDS", abbr: ["FRDS"], postal: "FRDS" },
	forest: { full: "FOREST", abbr: ["FRST", "FORESTS"], postal: "FRST" },
	forge: { full: "FORGE", abbr: ["FRG", "FORG"], postal: "FRG" },
	forges: { full: "FORGES", abbr: ["FRGS"], postal: "FRGS" },
	fork: { full: "FORK", abbr: ["FRK"], postal: "FRK" },
	forks: { full: "FORKS", abbr: ["FRKS"], postal: "FRKS" },
	fort: { full: "FORT", abbr: ["FT", "FRT"], postal: "FT" },
	freeway: { full: "FREEWAY", abbr: ["FWY", "FRWY", "FRWY", "FRWAY", "FREEWY"], postal: "FWY" },
	garden: { full: "GARDEN", abbr: ["GARDN", "GRDN", "GRDEN"], postal: "GDN" },
	gardens: { full: "GARDENS", abbr: ["GARDNS", "GRDNS", "GRDENS"], postal: "GDNS" },
	gateway: { full: "GATEWAY", abbr: [" GTWY", "GTWAY", "GATWAY", "GATEWY"], postal: "GTWY" },
	glen: { full: "GLEN", abbr: ["GLN"], postal: "GLN" },
	glens: { full: "GLENS", abbr: ["GLNS"], postal: "GLNS" },
	green: { full: "GREEN", abbr: ["GRN"], postal: "GRN" },
	greens: { full: "GREENS", abbr: ["GRNS"], postal: "GRNS" },
	grove: { full: "GROVE", abbr: ["GRV", "GROV"], postal: "GRV" },
	groves: { full: "GROVES", abbr: ["GRVS"], postal: "GRVS" },
	harbor: { full: "HARBOR", abbr: ["HARB", "HARBR", "HBR", "HRBR", "HRBOR"], postal: "HBR" },
	harbors: { full: "HARBORS", abbr: ["HARBS", "HARBRS", "HBRS", "HRBRS", "HRBORS"], postal: "HBRS" },
	haven: { full: "HAVEN", abbr: ["HVN"], postal: "HVN" },
	heights: { full: "HEIGHTS", abbr: ["HTS", "HT"], postal: "HTS" },
	highway: { full: "HIGHWAY", abbr: ["HIGHWY", "HWY", "HWAY", "HIWY", "HWAY"], postal: "HWY" },
	hill: { full: "HILL", abbr: ["HL"], postal: "HL" },
	hills: { full: "HILLS", abbr: ["HLS"], postal: "HLS" },
	hollow: { full: "HOLLOW", abbr: ["HOLW", "HOLLOWS", "HLLW", "HOLWS"], postal: "HOLW" },
	inlet: { full: "INLET", abbr: ["INLT"], postal: "INLT" },
	island: { full: "ISLAND", abbr: ["ISLND", "IS"], postal: "IS" },
	islands: { full: "ISLANDS", abbr: ["ISS", "ISLNDS"], postal: "ISS" },
	isle: { full: "ISLE", abbr: ["ISLES"], postal: "ISLE" },
	junction: { full: "JUNCTION", abbr: ["JCT", "JCTION", "JCTN", "JUNCTN", "JUNCTON"], postal: "JCT" },
	junctions: { full: "JUNCTIONS", abbr: ["JCTNS", "JCTS", "JCTIONS", "JUNCTNS", "JUNCTONS"], postal: "JCTS" },
	key: { full: "KEY", abbr: ["KY"], postal: "KY" },
	keys: { full: "KEYS", abbr: ["KYS"], postal: "KYS" },
	knoll: { full: "KNOLL", abbr: ["KNL", "KNOL"], postal: "KNL" },
	knolls: { full: "KNOLLS", abbr: ["KNLS"], postal: "KNLS" },
	lake: { full: "LAKE", abbr: ["LK"], postal: "LK" },
	lakes: { full: "LAKES", abbr: ["LKS"], postal: "LKS" },
	land: { full: "LAND", abbr: ["LAND", "LD"], postal: "LAND" },
	landing: { full: "LANDING", abbr: ["LNDG", "LNDNG"], postal: "LNDG" },
	lane: { full: "LANE", abbr: ["LN"], postal: "LN" },
	light: { full: "LIGHT", abbr: ["LGT"], postal: "LGT" },
	lights: { full: "LIGHTS", abbr: ["LGTS"], postal: "LGTS" },
	loaf: { full: "LOAF", abbr: ["LF"], postal: "LOAF" },
	lock: { full: "LOCK", abbr: ["LCK"], postal: "LCK" },
	locks: { full: "LOCKS", abbr: ["LCKS"], postal: "LCKS" },
	lodge: { full: "LODGE", abbr: ["LDG"], postal: "LDG" },
	loop: { full: "LOOP", abbr: ["LOOPS"], postal: "LOOP" },
	mall: { full: "MALL", abbr: ["MALL"], postal: "MALL" },
	manor: { full: "MANOR", abbr: ["MNR"], postal: "MNR" },
	manors: { full: "MANORS", abbr: ["MNRS"], postal: "MNRS" },
	meadow: { full: "MEADOW", abbr: ["MEDOW", "MDW"], postal: "MDW" },
	meadows: { full: "MEADOWS", abbr: ["MEDOWS", "MDWS"], postal: "MDWS" },
	mews: { full: "MEWS", abbr: ["MWS"], postal: "MEWS" },
	mill: { full: "MILL", abbr: ["ML"], postal: "ML" },
	mills: { full: "MILLS", abbr: ["MLS"], postal: "MLS" },
	mission: { full: "MISSION", abbr: ["MSN", "MISSN", "MSSN"], postal: "MSN" },
	mountain: { full: "MOUNTAIN", abbr: ["MTN", "MNTAIN", "MNTN", "MOUNTIN", "MTAIN", "MTIN"], postal: "MTN" },
	mountains: { full: "MOUNTAINS", abbr: ["MTNS", "MNTAINS", "MNTNS", "MOUNTINS", "MTAINS", "MTINS"], postal: "MTNS" },
	neck: { full: "NECK", abbr: ["NCK"], postal: "NCK" },
	orchard: { full: "ORCHARD", abbr: ["ORCH", "ORCHRD"], postal: "ORCH" },
	oval: { full: "OVAL", abbr: ["OVL"], postal: "OVAL" },
	overpass: { full: "OVERPASS", abbr: ["OPAS"], postal: "OPAS" },
	park: { full: "PARK", abbr: ["PRK"], postal: "PARK" },
	parks: { full: "PARKS", abbr: ["PRKS"], postal: "PARK" },
	parkway: { full: "PARKWAY", abbr: ["PARKWY", "PKWAY", "PKWY", "PKY"], postal: "PARKS" },
	parkways: { full: "PARKWAYS", abbr: ["PARKWYS", "PKWAYS", "PKWYS", "PKYS"], postal: "PKWY" },
	pass: { full: "PASS", abbr: ["PASS"], postal: "PASS" },
	passage: { full: "PASSAGE", abbr: ["PSSG", "PSGE", "PASSG", "PASSGE", "PSSGE"], postal: "PSGE" },
	path: { full: "PATH", abbr: ["PATHS"], postal: "PATH" },
	pike: { full: "PIKE", abbr: ["PIKES"], postal: "PIKE" },
	pine: { full: "PINE", abbr: ["PNE"], postal: "PNE" },
	pines: { full: "PINES", abbr: ["PNES"], postal: "PNES" },
	place: { full: "PLACE", abbr: ["PL"], postal: "PL" },
	plain: { full: "PLAIN", abbr: ["PLN"], postal: "PLN" },
	plains: { full: "PLAINS", abbr: ["PLNS"], postal: "PLNS" },
	plaza: { full: "PLAZA", abbr: ["PLZ", "PLZA"], postal: "PLZ" },
	point: { full: "POINT", abbr: ["PT"], postal: "PT" },
	points: { full: "POINTS", abbr: ["PTS"], postal: "PTS" },
	port: { full: "PORT", abbr: ["PRT"], postal: "PRT" },
	ports: { full: "PORTS", abbr: ["PRTS"], postal: "PRTS" },
	prairie: { full: "PRAIRIE", abbr: ["PRAIRIE", "PRR", "PR"], postal: "PR" },
	radial: { full: "RADIAL", abbr: ["RADIEL", "RADL", "RAD"], postal: "RADL" },
	ramp: { full: "RAMP", abbr: ["RAMP"], postal: "RAMP" },
	ranch: { full: "RANCH", abbr: ["RANCHES", "RNCH", "RNCHS"], postal: "RNCH" },
	rapid: { full: "RAPID", abbr: ["RPD"], postal: "RPD" },
	rapids: { full: "RAPIDS", abbr: ["RPDS"], postal: "RPDS" },
	rest: { full: "REST", abbr: ["RST"], postal: "RST" },
	ridge: { full: "RIDGE", abbr: ["RDGE", "RDG"], postal: "RDG" },
	ridges: { full: "RIDGES", abbr: ["RDGS"], postal: "RDGS" },
	river: { full: "RIVER", abbr: ["RIV", "RVR", "RIVR"], postal: "RIV" },
	road: { full: "ROAD", abbr: ["RD"], postal: "RD" },
	roads: { full: "ROADS", abbr: ["RDS"], postal: "RDS" },
	route: { full: "ROUTE", abbr: ["RTE"], postal: "RTE" },
	row: { full: "ROW", abbr: ["ROW"], postal: "ROW" },
	rue: { full: "RUE", abbr: ["RUE"], postal: "RUE" },
	run: { full: "RUN", abbr: ["RUN"], postal: "RUN" },
	shoal: { full: "SHOAL", abbr: ["SHL", "SHOL"], postal: "SHL" },
	shoals: { full: "SHOALS", abbr: ["SHLS", "SHOLS"], postal: "SHLS" },
	shore: { full: "SHORS", abbr: ["SHOAR", "SHR"], postal: "SHR" },
	shores: { full: "SHORES", abbr: ["SHOARS", "SHRS"], postal: "SHRS" },
	skyway: { full: "SKYWAY", abbr: ["SKYWY"], postal: "SKWY" },
	spring: { full: "SPRING", abbr: ["SPNG", "SPRNG", "SPG", "SPRG"], postal: "SPG" },
	springs: { full: "SPRINGS", abbr: ["SPNGS", "SPRNGS", "SPGS", "SPRGS"], postal: "SPRGS" },
	spur: { full: "SPUR", abbr: ["SPUR"], postal: "SPUR" },
	spurs: { full: "SPURS", abbr: ["SPURS"], postal: "SPURS" },
	square: { full: "SQUARE", abbr: ["SQ", "SQR", "SQRE", "SQU"], postal: "SQ" },
	squares: { full: "SQRS", abbr: ["SQS", "SQRS", "SQRES", "SQUS"], postal: "SQS" },
	station: { full: "STATION", abbr: ["STA", "STATN", "STN"], postal: "STA" },
	stravenue: { full: "STRAVENUE", abbr: ["STRA", "STRAV", "STRAVEN", "STRAVN", "STRVN", "STRVNUE"], postal: "STRA" },
	stream: { full: "STREAM", abbr: ["STREME", "STRM"], postal: "STRM" },
	street: { full: "STREET", abbr: ["STRT", "ST", "STR"], postal: "ST" },
	streets: { full: "STREETS", abbr: ["STS", "STRTS", "STRS"], postal: "STS" },
	summit: { full: "SUMMIT", abbr: ["SUMIT", "SUMITT", "SMT"], postal: "SMT" },
	terrace: { full: "TERRACE", abbr: ["TER", "TERR"], postal: "TER" },
	throughway: { full: "THROUGHWAY", abbr: ["THRUWAY", "THWAY", "TRWY"], postal: "TRWY" },
	trace: { full: "TRACE", abbr: ["TRACES", "TRCE"], postal: "TRCE" },
	track: { full: "TRACK", abbr: ["TRACKS", "TRAK", "TRK", "TRKS"], postal: "TRAK" },
	trafficway: { full: "TRAFFICWAY", abbr: ["TRFY", "TRFFCWY", "TRAFFWY", "TRAFWAY", "TRFWAY"], postal: "TRFY" },
	trail: { full: "TRAIL", abbr: ["TRAILS", "TRL", "TRLS"], postal: "TRL" },
	trailer: { full: "TRAILER", abbr: ["TRAILERS", "TRLR", "TRLRS"], postal: "TRLR" },
	tunnel: { full: "TUNNEL", abbr: ["TUNL", "TUNLS", "TUNEL", "TUNNELS", "TUNNL"], postal: "TUNL" },
	turnpike: { full: "TURNPIKE", abbr: ["TPKE", "TRNPKE", "TURNPK", "TRNPK"], postal: "TPKE" },
	underpass: { full: "UNDERPASS", abbr: ["UPAS"], postal: "UPAS" },
	union: { full: "UNION", abbr: ["UN"], postal: "UN" },
	unions: { full: "UNIONS", abbr: ["UNS"], postal: "UNS" },
	valley: { full: "VALLEY", abbr: ["VALLY", "VLLY", "VLY"], postal: "VLY" },
	valleys: { full: "VALLEYS", abbr: ["VLYS"], postal: "VLYS" },
	viaduct: { full: "VIADUCT", abbr: ["VIA", "VIADCT", "VDCT", "VDUCT"], postal: "VIA" },
	view: { full: "VIEW", abbr: ["VW"], postal: "VW" },
	views: { full: "VIEWS", abbr: ["VWS"], postal: "VWS" },
	village: { full: "VILLAGE", abbr: ["VILLAG", "VILL", "VILLG", "VILLIAGE", "VLG", "VILG"], postal: "VLG" },
	villages: { full: "VILLAGES", abbr: ["VILLAGS", "VILLS", "VILLGS", "VILLIAGES", "VLGS", "VILGS"], postal: "VLGS" },
	ville: { full: "VILLE", abbr: ["VL"], postal: "VL" },
	vista: { full: "VISTA", abbr: ["VIST", "VIS", "VST", "VSTA"], postal: "VIS" },
	walk: { full: "WALK", abbr: ["WALK"], postal: "WALK" },
	walks: { full: "WALKS", abbr: ["WALKS"], postal: "WALKS" },
	wall: { full: "WALL", abbr: ["WALL"], postal: "WALL" },
	way: { full: "WAY", abbr: ["WY"], postal: "WAY" },
	ways: { full: "WAYS", abbr: ["WYS"], postal: "WAYS" },
	well: { full: "WELL", abbr: ["WL"], postal: "WL" },
	wells: { full: "WELLS", abbr: ["WLS"], postal: "WLS" },
};

const postals = [
	" ALY ",
	" ANX ",
	" ARC ",
	" AVE ",
	" BYU ",
	" BCH ",
	" BND ",
	" BLF ",
	" BLFS ",
	" BTM ",
	" BLVD ",
	" BR ",
	" BRG ",
	" BRK ",
	" BRKS ",
	" BG ",
	" BGS ",
	" BYP ",
	" CP ",
	" CYN ",
	" CPE ",
	" CSWY ",
	" CTR ",
	" CTRS ",
	" CIR ",
	" CIRS ",
	" CLF ",
	" CLFS ",
	" CLB ",
	" CMN ",
	" CMNS ",
	" COR ",
	" CORS ",
	" CRSE ",
	" CT ",
	" CTS ",
	" CV ",
	" CVS ",
	" CRK ",
	" CRES ",
	" CRST ",
	" XING ",
	" XRD ",
	" XRDS ",
	" CURV ",
	" DL ",
	" DM ",
	" DV ",
	" DR ",
	" DRS ",
	" EST ",
	" ESTS ",
	" EXPY ",
	" EXT ",
	" EXTS ",
	" FALL ",
	" FLS ",
	" FRY ",
	" FLD ",
	" FLDS ",
	" FLT ",
	" FLTS ",
	" FRD ",
	" FRDS ",
	" FRST ",
	" FRG ",
	" FRGS ",
	" FRK ",
	" FRKS ",
	" FT ",
	" FWY ",
	" GDN ",
	" GDNS ",
	" GTWY ",
	" GLN ",
	" GLNS ",
	" GRN ",
	" GRNS ",
	" GRV ",
	" GRVS ",
	" HBR ",
	" HBRS ",
	" HVN ",
	" HTS ",
	" HWY ",
	" HL ",
	" HLS ",
	" HOLW ",
	" INLT ",
	" IS ",
	" ISS ",
	" ISLE ",
	" JCT ",
	" JCTS ",
	" KY ",
	" KYS ",
	" KNL ",
	" KNLS ",
	" LK ",
	" LKS ",
	" LAND ",
	" LNDG ",
	" LN ",
	" LGT ",
	" LGTS ",
	" LF ",
	" LCK ",
	" LCKS ",
	" LDG ",
	" LOOP ",
	" MALL ",
	" MNR ",
	" MNRS ",
	" MDW ",
	" MDWS ",
	" MEWS ",
	" ML ",
	" MLS ",
	" MSN ",
	" MTWY ",
	" MT ",
	" MTN ",
	" MTNS ",
	" NCK ",
	" ORCH ",
	" OVAL ",
	" OPAS ",
	" PARK ",
	" PARK ",
	" PKWY ",
	" PKWY ",
	" PASS ",
	" PSGE ",
	" PATH ",
	" PIKE ",
	" PNE ",
	" PNES ",
	" PL ",
	" PLN ",
	" PLNS ",
	" PLZ ",
	" PT ",
	" PTS ",
	" PRT ",
	" PRTS ",
	" PR ",
	" RADL ",
	" RAMP ",
	" RNCH ",
	" RPD ",
	" RPDS ",
	" RST ",
	" RDG ",
	" RDGS ",
	" RIV ",
	" RD ",
	" RDS ",
	" RTE ",
	" ROW ",
	" RUE ",
	" RUN ",
	" SHL ",
	" SHLS ",
	" SHR ",
	" SHRS ",
	" SKWY ",
	" SPG ",
	" SPGS ",
	" SPUR ",
	" SPUR ",
	" SQ ",
	" SQS ",
	" STA ",
	" STRA ",
	" STRM ",
	" ST ",
	" STS ",
	" SMT ",
	" TER ",
	" TRWY ",
	" TRCE ",
	" TRAK ",
	" TRFY ",
	" TRL ",
	" TRLR ",
	" TUNL ",
	" TPKE ",
	" UPAS ",
	" UN ",
	" UNS ",
	" VLY ",
	" VLYS ",
	" VIA ",
	" VW ",
	" VWS ",
	" VLG ",
	" VLGS ",
	" VL ",
	" VIS ",
	" WALK ",
	" WALK ",
	" WALL ",
	" WAY ",
	" WAYS ",
	" WL ",
	" WLS ",
];

// console.log(
// 	Object.keys(condensedArrayFull).map((key, index) => {
// 		const obj3 = {};
// 		obj3[key] = {
// 			...condensedArrayFull[key],
// 			postal: postals[index],
// 		};
// 		return obj3;
// 	})
// );

const condensedArrayFullComplete = {};
